/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import Admin.activityLogsForm;
import Admin.adminDashboard;
import Admin.usersForm;
import Config.Session;
import Config.dbConnector;
import eventm.loginForm;
import java.awt.Color;
import static java.awt.Color.white;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Jake
 */
public class bookingForm extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public bookingForm() {
        initComponents();
        displayData();
        
    }
     Color navcolor = new Color(37,61,44); 
        Color hovercolor = new Color(255,255,153); 
        boolean checkadd= true;
   public void displayData() {
    try {
        Session sess = Session.getInstance();
        int userId = sess.getUid();  

        dbConnector dbc = new dbConnector();
        String query = "SELECT e_id, b_date, b_status FROM tbl_bookings WHERE u_id = " + userId;
        ResultSet rs = dbc.getData(query);

        bktable.setModel(DbUtils.resultSetToTableModel(rs));
        rs.close();
    } catch (SQLException ex) {
        System.out.println("Error in displayData: " + ex.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        addlabel1 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        addlabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bktable = new javax.swing.JTable();
        eid = new javax.swing.JTextField();
        en = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bdate = new javax.swing.JTextField();
        es = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(37, 61, 44));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 210));
        jLabel1.setText("BOOKING FORM");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 210));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Log Out");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 814, 50));

        jPanel3.setBackground(new java.awt.Color(37, 61, 44));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-90.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, 100));

        acc_name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        acc_name.setForeground(new java.awt.Color(250, 250, 210));
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("USER");
        acc_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acc_nameMouseClicked(evt);
            }
        });
        jPanel3.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, -1));

        delete.setBackground(new java.awt.Color(37, 61, 44));
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(null);

        addlabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel.setForeground(new java.awt.Color(250, 250, 210));
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("DELETE");
        addlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabelMouseClicked(evt);
            }
        });
        delete.add(addlabel);
        addlabel.setBounds(0, 10, 170, 20);

        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 170, 40));

        add.setBackground(new java.awt.Color(37, 61, 44));
        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(null);

        addlabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel1.setForeground(new java.awt.Color(250, 250, 210));
        addlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel1.setText("ADD");
        addlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel1MouseClicked(evt);
            }
        });
        add.add(addlabel1);
        addlabel1.setBounds(0, 10, 170, 20);

        jPanel3.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 170, 40));

        update.setBackground(new java.awt.Color(37, 61, 44));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        addlabel2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel2.setForeground(new java.awt.Color(250, 250, 210));
        addlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel2.setText("UPDATE");
        addlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel2MouseClicked(evt);
            }
        });
        update.add(addlabel2);
        addlabel2.setBounds(0, 10, 170, 20);

        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 170, 460));

        bktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        bktable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bktableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bktable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 330, 370));

        eid.setEnabled(false);
        jPanel1.add(eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 170, 40));

        en.setEnabled(false);
        jPanel1.add(en, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 210, 40));

        jLabel4.setBackground(new java.awt.Color(37, 61, 44));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 61, 44));
        jLabel4.setText("Event Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel5.setBackground(new java.awt.Color(37, 61, 44));
        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 61, 44));
        jLabel5.setText("BOOKED EVENTS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel6.setBackground(new java.awt.Color(37, 61, 44));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 61, 44));
        jLabel6.setText("Status:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));
        jPanel1.add(bdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 210, 40));

        es.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        es.setForeground(new java.awt.Color(37, 61, 44));
        es.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved" }));
        es.setEnabled(false);
        jPanel1.add(es, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 210, 40));

        jLabel7.setBackground(new java.awt.Color(37, 61, 44));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 61, 44));
        jLabel7.setText("Date:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel8.setBackground(new java.awt.Color(37, 61, 44));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 61, 44));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-23.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 40, 40));

        jLabel9.setBackground(new java.awt.Color(37, 61, 44));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 61, 44));
        jLabel9.setText("Event ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         loginForm lfr= new loginForm();
              lfr.setVisible(true);
              this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void acc_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acc_nameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_nameMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         Session sess =Session.getInstance();
        
        if(sess.getUid()== 0){
             JOptionPane.showMessageDialog(null,"No Account Found, Login First!");
            loginForm lf = new loginForm();
            lf.setVisible(true);
            this.dispose(); 
        }else{
            acc_name.setText(""+sess.getFname());
            
        }
      
    }//GEN-LAST:event_formWindowActivated

    private void bktableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bktableMouseClicked
      
    }//GEN-LAST:event_bktableMouseClicked

    private void addlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabelMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
           eid.setText("");
            en.setText("");
            bdate.setText("");
            es.setSelectedIndex(0);
    

    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        delete.setBackground(hovercolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseExited

    private void addlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel1MouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
     Session sess = Session.getInstance();

if (eid.getText().isEmpty() || en.getText().isEmpty() || bdate.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "All fields are required!");
} else {
    dbConnector dbc = new dbConnector();
    int userId = sess.getUid();
    String eventId = eid.getText();
    String bookingDate = bdate.getText();
    String bookingStatus = es.getSelectedItem().toString();

    
    String sql = "INSERT INTO tbl_bookings(u_id, e_id, b_date, b_status) VALUES(" 
                 + userId + ", " 
                 + eventId + ", '" 
                 + bookingDate + "', '" 
                 + bookingStatus + "')";

    if (dbc.insertData(sql)) {
        JOptionPane.showMessageDialog(null, "Event booked successfully!");

       
        String action = "User booked an event with ID: " + eventId;
        activityLogsForm logger = new activityLogsForm();
        logger.logActivity(action, Integer.parseInt(eventId)); 
    }


}
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        add.setBackground(hovercolor);
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        add.setBackground(navcolor);
    }//GEN-LAST:event_addMouseExited

    private void addlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel2MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
         update.setBackground(hovercolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
         update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
       bookingTable et= new bookingTable();
        et.setVisible(true);
        
                
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_name;
    private javax.swing.JPanel add;
    private javax.swing.JLabel addlabel;
    private javax.swing.JLabel addlabel1;
    private javax.swing.JLabel addlabel2;
    private javax.swing.JTextField bdate;
    private javax.swing.JTable bktable;
    private javax.swing.JPanel delete;
    public javax.swing.JTextField eid;
    public javax.swing.JTextField en;
    private javax.swing.JComboBox<String> es;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
