/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Config.Session;
import Config.dbConnector;
import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jake
 */
public class eventForm extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public eventForm() {
        initComponents();
        displayData();
    }
    boolean checkadd= true;
     Color navcolor = new Color(37,61,44); 
        Color hovercolor = new Color(102,102,0); 
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT e_id, e_name, e_capacity, e_status FROM tbl_events");
            etable.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());

        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        etable = new javax.swing.JTable();
        print = new javax.swing.JPanel();
        p_edit1 = new javax.swing.JLabel();
        p_add = new javax.swing.JPanel();
        addlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acc_id = new javax.swing.JLabel();
        clear = new javax.swing.JPanel();
        addlabel1 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        addlabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        addlabel3 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        es = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        en = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        el = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ec = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ep = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(250, 250, 210));

        jPanel2.setBackground(new java.awt.Color(37, 61, 44));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 210));
        jLabel1.setText("EVENTS FORM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 30, 123, 25);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 210));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Back");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(740, 20, 44, 20);

        jPanel3.setBackground(new java.awt.Color(37, 61, 44));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        etable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(etable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 280));

        print.setBackground(new java.awt.Color(37, 61, 44));
        print.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                printMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                printMouseExited(evt);
            }
        });
        print.setLayout(null);

        p_edit1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        p_edit1.setForeground(new java.awt.Color(250, 250, 210));
        p_edit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_edit1.setText("PRINT");
        p_edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_edit1MouseEntered(evt);
            }
        });
        print.add(p_edit1);
        p_edit1.setBounds(10, 10, 150, 20);

        jPanel3.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 180, 40));

        p_add.setBackground(new java.awt.Color(37, 61, 44));
        p_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        p_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_addMouseExited(evt);
            }
        });
        p_add.setLayout(null);

        addlabel.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel.setForeground(new java.awt.Color(250, 250, 210));
        addlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel.setText("ADD");
        addlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabelMouseClicked(evt);
            }
        });
        p_add.add(addlabel);
        addlabel.setBounds(0, 10, 180, 20);

        jPanel3.add(p_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 210));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Current User:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 180, 30));

        acc_id.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        acc_id.setForeground(new java.awt.Color(250, 250, 210));
        acc_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_id.setText("ID");
        jPanel3.add(acc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 120, 20));

        clear.setBackground(new java.awt.Color(37, 61, 44));
        clear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearMouseExited(evt);
            }
        });
        clear.setLayout(null);

        addlabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel1.setForeground(new java.awt.Color(250, 250, 210));
        addlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel1.setText("CLEAR");
        addlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel1MouseClicked(evt);
            }
        });
        clear.add(addlabel1);
        addlabel1.setBounds(0, 10, 180, 20);

        jPanel3.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 180, 40));

        update.setBackground(new java.awt.Color(37, 61, 44));
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.setLayout(null);

        addlabel2.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel2.setForeground(new java.awt.Color(250, 250, 210));
        addlabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel2.setText("UPDATE");
        addlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel2MouseClicked(evt);
            }
        });
        update.add(addlabel2);
        addlabel2.setBounds(0, 10, 180, 20);

        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 40));

        delete.setBackground(new java.awt.Color(37, 61, 44));
        delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 250, 210)));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.setLayout(null);

        addlabel3.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        addlabel3.setForeground(new java.awt.Color(250, 250, 210));
        addlabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addlabel3.setText("DELETE");
        addlabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addlabel3MouseClicked(evt);
            }
        });
        delete.add(addlabel3);
        addlabel3.setBounds(0, 10, 180, 20);

        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 40));

        eid.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(37, 61, 44));
        jLabel8.setText("Event ID:");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(37, 61, 44));
        jLabel7.setText("Status:");

        es.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        es.setForeground(new java.awt.Color(37, 61, 44));
        es.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Unavailable" }));
        es.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(37, 61, 44));
        jLabel9.setText("Event Name:");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(37, 61, 44));
        jLabel10.setText("Location:");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(37, 61, 44));
        jLabel11.setText("Capacity:");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(37, 61, 44));
        jLabel12.setText("Price:");

        jPanel4.setLayout(null);
        jPanel4.add(image);
        image.setBounds(10, 11, 180, 144);

        select.setBackground(new java.awt.Color(204, 204, 204));
        select.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        select.setForeground(new java.awt.Color(37, 61, 44));
        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(204, 204, 204));
        remove.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        remove.setForeground(new java.awt.Color(37, 61, 44));
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ep)
                    .addComponent(ec)
                    .addComponent(el)
                    .addComponent(en)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(es, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(es, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(el, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        adminDashboard ds= new adminDashboard();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess =Session.getInstance();
        acc_id.setText(""+sess.getUid());
    }//GEN-LAST:event_formWindowActivated

    private void p_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseEntered
     p_add.setBackground(hovercolor);
    }//GEN-LAST:event_p_addMouseEntered

    private void p_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseExited
    p_add.setBackground(navcolor);
    }//GEN-LAST:event_p_addMouseExited

    private void p_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_addMouseClicked
        if(checkadd){
            
            if(en.getText().isEmpty()|| ep.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All fields are required!");
            
            }else{
                  dbConnector dbc= new dbConnector();
                    dbc.insertData("INSERT INTO tbl_events(e_name, e_price, e_status,e_location,e_capacity,e_image)VALUES('"+en.getText()+"', '"+ep.getText() +"', '"+es.getSelectedItem()+"','"+el.getText()+"','"+ec.getText()+"','')");
                     JOptionPane.showMessageDialog(null,"Successfully Added!");
                     displayData();
                     
                     checkadd= true;
                   addlabel.setForeground(white);
                   eid.setText("");
                   en.setText("");
                   el.setText("");
                   ec.setText("");
                   ep.setText("");
                   es.setSelectedIndex(0);
                    }
               
              
        }else{
            JOptionPane.showMessageDialog(null,"Clear the Field First");
         }
        
    }//GEN-LAST:event_p_addMouseClicked

    private void addlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabelMouseClicked

    private void p_edit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_edit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_p_edit1MouseEntered

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
     
    }//GEN-LAST:event_printMouseClicked

    private void printMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseEntered
        print.setBackground(hovercolor);
    }//GEN-LAST:event_printMouseEntered

    private void printMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseExited
        print.setBackground(navcolor);
    }//GEN-LAST:event_printMouseExited

    private void esActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
       
    }//GEN-LAST:event_selectActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       
    }//GEN-LAST:event_removeActionPerformed

    private void etableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etableMouseClicked
       int rowIndex= etable.getSelectedRow();
        
        if(rowIndex < 0){
            JOptionPane.showMessageDialog(null,"Please Select an Item!");
        }else{
            try{
            dbConnector dbc= new dbConnector();
            TableModel tbl= etable.getModel();
            ResultSet rs = dbc.getData("SELECT*FROM tbl_events WHERE e_id ='"+tbl.getValueAt(rowIndex, 0)+"'");
            if(rs.next()){
            eid.setText(""+rs.getInt("e_id"));
            en.setText(""+rs.getString("e_name"));
            el.setText(""+rs.getString("e_location"));
            ec.setText(""+rs.getString("e_capacity"));
            ep.setText(""+rs.getString("e_price"));
            es.setSelectedItem(""+rs.getString("e_status"));
            p_add.setEnabled(false);
            addlabel.setForeground(red);
            checkadd= false;
             }
        }catch(SQLException ex){
                System.out.println(""+ex);
        }
            
        }       
                
         TableModel tbl= etable.getModel();
    }//GEN-LAST:event_etableMouseClicked

    private void addlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel1MouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
         checkadd= true;
         addlabel.setForeground(white);
         eid.setText("");
            en.setText("");
            el.setText("");
            ec.setText("");
            ep.setText("");
            es.setSelectedIndex(0);
    }//GEN-LAST:event_clearMouseClicked

    private void clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseEntered
       clear.setBackground(hovercolor);
    }//GEN-LAST:event_clearMouseEntered

    private void clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseExited
        clear.setBackground(navcolor);
    }//GEN-LAST:event_clearMouseExited

    private void addlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel2MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        if(eid.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please select a product first!");
        }else{
             if(en.getText().isEmpty()|| ep.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"All fields are required!");
        }else{
            dbConnector dbc = new dbConnector();
            dbc.updateData("UPDATE tbl_events SET e_name= '"+en.getText()+"',e_location='"+el.getText()+"',e_capacity='"+ec.getText()+"'"
                    + ",e_price='"+ep.getText()+"',e_status='"+es.getSelectedItem()+"'"
                    + " WHERE e_id= '"+eid.getText()+"'");
                    JOptionPane.showMessageDialog(null,"Updated Successfully!");
                      displayData();
                     checkadd= true;
                   addlabel.setForeground(white);
                   eid.setText("");
                   en.setText("");
                   el.setText("");
                   ec.setText("");
                   ep.setText("");
                   es.setSelectedIndex(0);
             }
        }
    }//GEN-LAST:event_updateMouseClicked

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        update.setBackground(hovercolor);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
         update.setBackground(navcolor);
    }//GEN-LAST:event_updateMouseExited

    private void addlabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addlabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addlabel3MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
          delete.setBackground(hovercolor);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(navcolor);
    }//GEN-LAST:event_deleteMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eventForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eventForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc_id;
    private javax.swing.JLabel addlabel;
    private javax.swing.JLabel addlabel1;
    private javax.swing.JLabel addlabel2;
    private javax.swing.JLabel addlabel3;
    private javax.swing.JPanel clear;
    private javax.swing.JPanel delete;
    public javax.swing.JTextField ec;
    public javax.swing.JTextField eid;
    public javax.swing.JTextField el;
    public javax.swing.JTextField en;
    public javax.swing.JTextField ep;
    public javax.swing.JComboBox<String> es;
    private javax.swing.JTable etable;
    public javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JPanel p_add;
    private javax.swing.JLabel p_edit1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JPanel print;
    public javax.swing.JButton remove;
    public javax.swing.JButton select;
    private javax.swing.JPanel update;
    // End of variables declaration//GEN-END:variables
}
